package com.example.fitapp.Gemini_helpers;

/**
 * Interface for handling callbacks from Gemini AI operations.
 * Provides methods to handle successful responses and operation failures.
 */
public interface GeminiCallback {
    /**
     * Called when the Gemini operation completes successfully.
     *
     * @param result The text result generated by the AI model.
     */
    void onSuccess(String result);

    /**
     * Called when the Gemini operation fails.
     *
     * @param error The exception or error that caused the failure.
     */
    void onFailure(Throwable error);
}
